fr:
  languageCode: fr
  title: "presque-quelque-chose" # Titre pour la version FR
  weight: 1
  # Indique à Hugo de chercher le contenu FR dans ce dossier :
  contentDir: content/fr

en:
  languageCode: en
  title: "almost-something" # Titre pour la version EN
  weight: 2
  # Indique à Hugo de chercher le contenu EN dans ce dossier :
  contentDir: content/en