main:
  - name: le guichet
    url: /
    weight: 10
  - name: inutilités appliquées
    url: /inutilités-appliquées/
    weight: 20
  - name: solutions imaginaires
    url: /solutions-imaginaires/
    weight: 30
  - name: recherches
    url: /recherches/
    weight: 40
  - name: ondes & pixels
    url: /ondes-pixels/
    weight: 50
  # === DEBUT DU NOUVEAU BLOC ===
  - name: Se connecter
    url: '#'
    weight: 60
    identifier: login_link
  # === FIN DU NOUVEAU BLOC ===