main:
  - name: atelier
    url: /
    weight: 10
  - name: inutilités appliquées
    url: /inutilités-appliquées/
    weight: 20
  - name: solutions imaginaires
    url: /solutions-imaginaires/
    weight: 30
  - name: recherches
    url: /recherches/
    weight: 40
  - name: ondes & pixels
    url: /ondes-pixels/
    weight: 50
  - name: almanach
    url: /almanach/  # pointe vers votre dossier content/agenda
    weight: 60